- hosts: localhost
  gather_facts: no
  vars_files:
          - /root/arth_workspace/ansible/role/k8s-multi-node-cluter-on-aws/ec2-key.yml
  tasks:
      - pip:
          name: boto3
          state: present

      - name: Launch AWS instance for k8s-master-node
        ec2:
            aws_access_key: "{{ accesskey }}"
            aws_secret_key: "{{ secretkey }}"
            image: ami-08f63db601b82ff5f
            wait: yes
            count: 1
            instance_tags:
                  name: master
            instance_type: t2.micro
            key_name: my-key
            group_id: sg-0246b21430258f274
            assign_public_ip: yes
            region: ap-south-1
            vpc_subnet_id: subnet-580c3630

      - name: Launch AWS instance for k8s-slave-node
        ec2:
            aws_access_key: "{{ accesskey }}"
            aws_secret_key: "{{ secretkey }}"
            image: ami-08f63db601b82ff5f
            wait: yes
            count: 2
            instance_tags:
                  name: slave
            instance_type: t2.micro
            key_name: my-key
            group_id: sg-0246b21430258f274
            assign_public_ip: yes
            region: ap-south-1
            vpc_subnet_id: subnet-580c3630

