- hosts: tag_name_master
  tasks:
  - name: Creating Join Token
    shell: "kubeadm token  create --print-join-command"
    register: join_token

  - set_fact:
      shared_variable: "{{ join_token.stdout }}"

  - add_host:
      name: "join"
      shared_variable: "{{ shared_variable }}"

- hosts: tag_name_slave
  vars:
    join_slave: "{{ hostvars['join']['shared_variable'] }}"
  tasks:
  - name: Joining slave to master node
    shell: "{{ join_slave }}"






- hosts: tag_name_master
  tasks:
  - name: Creating Join Token
    shell: "kubeadm token  create --print-join-command"
    register: join

  - set_fact:
      shared_variable: "{{ join.stdout }}"

  - add_host:
      name: "value"
      shared_variable: "{{ shared_variable }}"

- hosts: tag_name_slave
  vars:
    join_slave: "{{ hostvars['value']['shared_variable'] }}"
  tasks:
  - name: Joining slave to master node
    shell: "{{ join_slave }}"
