---
# tasks file for slave-node

- name: Configuring Yum repo for K8s
  yum_repository:
        name: k8s_repo
        description: Yum for kubectl kubeadm
        file: k8srepo
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
        gpgcheck: yes
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        enabled: yes

- name: Installing Docker, Kubeadm, Kubectl, Kubelet & iproute-tc
  package:
     name:
        - docker
        - kubeadm
        - kubectl
        - kubelet
        - iproute-tc

- name: Docker cgroup drive changed to systemd
  copy:
    dest: /etc/docker/daemon.json
    content: |
            {
             "exec-opts": ["native.cgroupdriver=systemd"]
            }

- name: Restart docker service
  service:
      name: docker
      state: restarted
      enabled: yes

- name: Restarting kubelet
  service:
     name: kubelet
     state: restarted
     enabled: yes

- name: iptable
  copy:
     content: |
             net.bridge.bridge-nf-call-ip6tables=1
             net.bridge.bridge-nf-call-iptables=1
     dest: /etc/sysctl.d/k8s.conf

- name: Refreshing system
  shell: sudo sysctl --system
